# Datos del participante
Nombre: Diego Eduardo Rodríguez Guzmán 

Fecha: 20/05/2026

# Control hospitalario

Utiliza las secciones pertinentes para colocar la solución a cada uno de los requerimientos solicitados.

## Importa las librerías pertinentes para solucionar el reto.

In [42]:
import pandas as pd
import numpy as np

## Extrae la información del archivo.

In [43]:
df = pd.read_excel("hospitalData.xlsx")
df.head()

,Week Ending Date,Geographic aggregation,Number of Inpatient Beds,Number of Adult Inpatient Beds,Number of Pediatric Inpatient beds,Number of Inpatient Beds Occupied,Number of Adult Inpatient Beds Occupied,Number of Pediatric Inpatient Beds Occupied,Number of ICU Beds,Number of Adult ICU Beds,...,Number of ICU Beds Occupied,Number of Adult ICU Beds Occupied,Number of Pediatric ICU Beds Occupied,Number of Adult Patients Hospitalized with COVID-19,Number of Pediatric Patients Hospitalized with COVID-19,Number of Adult Patients Hospitalized with Influenza,Number of Pedatric Patients Hospitalized with Influenza,Number of Adult Patients Hospitalized with RSV,Number of Pediatric Patients Hospitalized with RSV,Certifications
0,12/08/23,WA,10650.0,9282.0,482.0,9040.0,8117.0,339.0,1623.0,1059.0,...,1309.0,845.0,62.0,222.0,4.0,NaN,NaN,NaN,NaN,DWC/CARN/CRN/CBN/CBN/CPEN/DWC/CPEN/CPAN/ACS
1,12/08/23,WI,10752.0,9824.0,425.0,7574.0,7027.0,286.0,1566.0,1232.0,...,1014.0,817.0,71.0,84.0,2.0,NaN,NaN,NaN,NaN,AOCNP/ACS/CARN/CRN
2,12/08/23,WV,4813.0,4556.0,256.0,3701.0,3562.0,139.0,639.0,595.0,...,468.0,446.0,23.0,47.0,0.0,NaN,NaN,NaN,NaN,CRN
3,12/08/23,WY,1318.0,1142.0,25.0,559.0,534.0,6.0,114.0,109.0,...,40.0,40.0,0.0,4.0,0.0,NaN,NaN,NaN,NaN,AOCNP/JCI/CARN/CBN/CARN/JCI/ACS
4,19/08/23,AK,1354.0,1192.0,77.0,1054.0,939.0,43.0,184.0,126.0,...,139.0,86.0,8.0,11.0,1.0,NaN,NaN,NaN,NaN,CARN/ISO/AOCNP/CARN

## Muestra la estructura y los tipos de datos de cada columna para identificar qué operaciones puedes realizar con cada una de ellas, asegúrandote de que las columnas con fechas sean del tipo datetime64.

In [44]:
df["Week Ending Date"] = pd.to_datetime(df["Week Ending Date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12768 entries, 0 to 12767
Data columns (total 21 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Week Ending Date                                         12768 non-null  datetime64[ns]
 1   Geographic aggregation                                   12768 non-null  object
 2   Number of Inpatient Beds                                 12521 non-null  float64
 3   Number of Adult Inpatient Beds                           12506 non-null  float64
 4   Number of Pediatric Inpatient beds                       12485 non-null  float64
 5   Number of Inpatient Beds Occupied                        12521 non-null  float64
 6   Number of Adult Inpatient Beds Occupied                  12510 non-null  float64
 7   Number of Pediatric Inpatient Beds Occupied              12494 non-null  float64
 8   Number of ICU Beds                                       12521 non-null  float64
 9   Number of Adult ICU Beds                                 12506 non-null  float64
 10  Number of Pediatric ICU Beds                             12485 non-null  float64
 11  Number of ICU Beds Occupied                              12521 non-null  float64
 12  Number of Adult ICU Beds Occupied                        12510 non-null  float64
 13  Number of Pediatric ICU Beds Occupied                    12494 non-null  float64
 14  Number of Adult Patients Hospitalized with COVID-19      12508 non-null  float64
 15  Number of Pediatric Patients Hospitalized with COVID-19  12499 non-null  float64
 16  Number of Adult Patients Hospitalized with Influenza     2034 non-null   float64
 17  Number of Pedatric Patients Hospitalized with Influenza  2028 non-null   float64
 18  Number of Adult Patients Hospitalized with RSV           2111 non-null   float64
 19  Number of Pediatric Patients Hospitalized with RSV       2109 non-null   float64
 20  Certifications                                           12768 non-null  object
dtypes: datetime64[ns](1), float64(18), object(2)
memory usage: 2.0+ MB

C:\Users\diego\AppData\Local\Temp\ipykernel_22692\3018076845.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Week Ending Date"] = pd.to_datetime(df["Week Ending Date"])

## Elimina los registros con el código geográfico MP.

In [45]:
df = df[df["Geographic aggregation"] != "MP"]

# Para las columnas que tienen que ver con la ICU, cambia los valores faltantes por 0.

In [46]:
df[["Number of ICU Beds","Number of Adult ICU Beds","Number of Pediatric ICU Beds","Number of ICU Beds Occupied","Number of Adult ICU Beds Occupied","Number of Pediatric ICU Beds Occupied"]] = df[["Number of ICU Beds","Number of Adult ICU Beds","Number of Pediatric ICU Beds","Number of ICU Beds Occupied","Number of Adult ICU Beds Occupied","Number of Pediatric ICU Beds Occupied"]].fillna(0)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12544 entries, 0 to 12767
Data columns (total 21 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Week Ending Date                                         12544 non-null  datetime64[ns]
 1   Geographic aggregation                                   12544 non-null  object
 2   Number of Inpatient Beds                                 12421 non-null  float64
 3   Number of Adult Inpatient Beds                           12417 non-null  float64
 4   Number of Pediatric Inpatient beds                       12399 non-null  float64
 5   Number of Inpatient Beds Occupied                        12421 non-null  float64
 6   Number of Adult Inpatient Beds Occupied                  12421 non-null  float64
 7   Number of Pediatric Inpatient Beds Occupied              12408 non-null  float64
 8   Number of ICU Beds                                       12544 non-null  float64
 9   Number of Adult ICU Beds                                 12544 non-null  float64
 10  Number of Pediatric ICU Beds                             12544 non-null  float64
 11  Number of ICU Beds Occupied                              12544 non-null  float64
 12  Number of Adult ICU Beds Occupied                        12544 non-null  float64
 13  Number of Pediatric ICU Beds Occupied                    12544 non-null  float64
 14  Number of Adult Patients Hospitalized with COVID-19      12408 non-null  float64
 15  Number of Pediatric Patients Hospitalized with COVID-19  12399 non-null  float64
 16  Number of Adult Patients Hospitalized with Influenza     2034 non-null   float64
 17  Number of Pedatric Patients Hospitalized with Influenza  2028 non-null   float64
 18  Number of Adult Patients Hospitalized with RSV           2111 non-null   float64
 19  Number of Pediatric Patients Hospitalized with RSV       2109 non-null   float64
 20  Certifications                                           12544 non-null  object
dtypes: datetime64[ns](1), float64(18), object(2)
memory usage: 2.1+ MB

# Conoce el periodo de registro que se encuentra en el archivo para saber cuántos días han transcurrido entre la fecha más reciente y la más antigua.

In [47]:
df["Week Ending Date"].max() - df["Week Ending Date"].min()

Timedelta('1736 days 00:00:00')

# Obtén la cantidad total de pacientes pediátricos hospitalizados con COVID-19.

In [48]:
ped_covid = df["Number of Pediatric Patients Hospitalized with COVID-19"].sum()
print(f"Total de paciented pediatricos hospitalizados con COVID-19: {ped_covid}")

Total de paciented pediatricos hospitalizados con COVID-19: 295180.0

# Obtén el promedio de pacientes adultos hospitalizados por RSV.

In [49]:
adult_mean = df["Number of Adult Patients Hospitalized with COVID-19"].mean()
print(f"Promedio de pacientes adultos hospitalizados con COVID-19: {adult_mean.round(2)}")

Promedio de pacientes adultos hospitalizados con COVID-19: 1198.41

# Agrupa por región geográfica y obtén la sumatoria de pacientes adultos hospitalizados con influenza.

In [50]:
df['Number of Adult Patients Hospitalized with Influenza'].groupby(df['Geographic aggregation']).sum()

Geographic aggregation
AK       19.0
AL      168.0
AR       99.0
AS        0.0
AZ      398.0
CA      713.0
CO       39.0
CT       63.0
DC       12.0
DE       85.0
FL      663.0
GA      247.0
GU        8.0
HI       44.0
IA       34.0
ID       54.0
IL      166.0
IN      134.0
KS       68.0
KY      134.0
LA      199.0
MA       16.0
MD       31.0
ME       43.0
MI       57.0
MN      126.0
MO       65.0
MS       90.0
MT       22.0
NC      393.0
ND        9.0
NE       25.0
NH       31.0
NJ       69.0
NM       30.0
NV       73.0
NY      759.0
OH     1412.0
OK      303.0
OR       36.0
PA     1684.0
PR      214.0
RI      101.0
SC       64.0
SD        7.0
TN      141.0
TX      430.0
USA    9837.0
UT       30.0
VA      110.0
VI        0.0
VT       11.0
WA       37.0
WI       20.0
WV        3.0
WY       15.0
Name: Number of Adult Patients Hospitalized with Influenza, dtype: float64

# Crea una columna derivada llamada "Percent of Adult ICU Beds Occupied" con el porcentaje de ocupación para las camas de los adultos en la ICU.

In [51]:
df['Percent of Adults ICU Beds Occupied'] = df['Number of Adult ICU Beds Occupied'] / df['Number of Adult ICU Beds'] * 100
df['Percent of Adults ICU Beds Occupied']

0        79.792257
1        66.314935
2        74.957983
3        36.697248
4        68.253968
           ...
12763    71.000474
12764    64.230769
12765    64.008621
12766    50.000000
12767    67.708333
Name: Percent of Adults ICU Beds Occupied, Length: 12544, dtype: float64

# Crea un *dataframe* llamado "filtro", con las filas de los hospitales que tengan más de 300 camas "disponibles" para adultos en la ICU; y las columnas de identificación geográfica y las relacionadas, con la cantidad de pacientes con alguna de las enfermedades respiratorias de los adultos.

In [52]:
filtro = df.loc[
    df['Number of Adult ICU Beds'] - df['Number of Adult ICU Beds Occupied'] > 300,
    [
        'Geographic aggregation',
        'Number of Adult ICU Beds',
        'Number of Adult ICU Beds Occupied',
        'Number of Adult Patients Hospitalized with COVID-19',
        'Number of Adult Patients Hospitalized with Influenza'
    ]
]
filtro

,Geographic aggregation,Number of Adult ICU Beds,Number of Adult ICU Beds Occupied,Number of Adult Patients Hospitalized with COVID-19,Number of Adult Patients Hospitalized with Influenza
1,WI,1232.0,817.0,84.0,NaN
8,AZ,1524.0,1036.0,128.0,NaN
9,CA,6490.0,4525.0,1412.0,NaN
10,CO,1275.0,768.0,80.0,NaN
14,FL,6442.0,4706.0,1563.0,NaN
...,...,...,...,...,...
12759,SC,1239.0,824.0,154.0,NaN
12761,TN,2408.0,1584.0,164.0,NaN
12762,TX,5695.0,4820.0,786.0,NaN
12763,USA,75984.0,53949.0,9333.0,NaN
12765,VA,1856.0,1188.0,155.0,NaN

# Crea un *dataframe* llamado "registros2024" que tenga todos los registros del año 2024.

In [53]:
registros2024 = df[df['Week Ending Date'].dt.year == 2024]
registros2024

,Week Ending Date,Geographic aggregation,Number of Inpatient Beds,Number of Adult Inpatient Beds,Number of Pediatric Inpatient beds,Number of Inpatient Beds Occupied,Number of Adult Inpatient Beds Occupied,Number of Pediatric Inpatient Beds Occupied,Number of ICU Beds,Number of Adult ICU Beds,...,Number of Adult ICU Beds Occupied,Number of Pediatric ICU Beds Occupied,Number of Adult Patients Hospitalized with COVID-19,Number of Pediatric Patients Hospitalized with COVID-19,Number of Adult Patients Hospitalized with Influenza,Number of Pedatric Patients Hospitalized with Influenza,Number of Adult Patients Hospitalized with RSV,Number of Pediatric Patients Hospitalized with RSV,Certifications,Percent of Adults ICU Beds Occupied
1144,2024-06-01,AK,1351.0,1189.0,75.0,1014.0,891.0,47.0,188.0,126.0,...,84.0,7.0,28.0,1.0,0.0,0.0,0.0,1.0,CPEN/DWC/CPEN/DWC/CPEN/CPAN,66.666667
1145,2024-06-01,AL,12547.0,11735.0,497.0,10010.0,9365.0,304.0,1597.0,1519.0,...,1323.0,42.0,430.0,28.0,NaN,NaN,NaN,NaN,DWC,87.096774
1146,2024-06-01,AR,7642.0,7022.0,422.0,5297.0,4857.0,306.0,1216.0,939.0,...,688.0,55.0,238.0,6.0,6.0,0.0,4.0,0.0,DWC,73.269436
1147,2024-06-01,AS,150.0,122.0,28.0,83.0,63.0,14.0,7.0,7.0,...,5.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,CRN/AOCNP/CRN/CCTN/DWC,71.428571
1148,2024-06-01,AZ,13449.0,11839.0,877.0,11340.0,10002.0,702.0,2047.0,1539.0,...,1141.0,224.0,441.0,28.0,18.0,0.0,3.0,4.0,DWC/CCTN/CRN/CRN/AOCNP,74.139051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3761,2024-11-16,VT,1038.0,898.0,126.0,723.0,673.0,50.0,110.0,80.0,...,51.0,21.0,8.0,0.0,0.0,0.0,0.0,1.0,CRN/ACS/CARN/CPEN/CPEN/DWC/JCI,63.750000
3762,2024-11-16,WA,10653.0,9449.0,1154.0,9230.0,8307.0,920.0,1502.0,1009.0,...,799.0,392.0,93.0,3.0,14.0,1.0,11.0,9.0,CPEN/ISO/AOCNP/CARN/CCTN/AOCNP/CRN/CPEN/CRN,79.187314
3763,2024-11-16,WI,11146.0,9756.0,1334.0,8060.0,7209.0,823.0,1675.0,1179.0,...,840.0,349.0,95.0,6.0,3.0,0.0,1.0,4.0,ISO/CPEN/CBN/CBN/CPEN,71.246819
3764,2024-11-16,WV,5723.0,4944.0,779.0,3930.0,3682.0,243.0,794.0,660.0,...,515.0,95.0,63.0,1.0,2.0,0.0,3.0,2.0,CPAN/CCTN/CCTN/CRN/ISO/CPAN,78.030303
3765,2024-11-16,WY,919.0,817.0,43.0,359.0,345.0,5.0,80.0,77.0,...,28.0,0.0,11.0,0.0,1.0,0.0,0.0,0.0,JCI/CBN/ISO/JCI/ACS/ISO/CRN/JCI,36.363636

# Crear una columna derivada con el conteo de la cantidad de certificaciones que tiene cada hospital; es decir, cuenta la cantidad de elementos que hay en la columna de certificaciones separándolas con /

In [54]:
df['Cert_Counter'] = df['Certifications'].str.split('/').str.len()
df

,Week Ending Date,Geographic aggregation,Number of Inpatient Beds,Number of Adult Inpatient Beds,Number of Pediatric Inpatient beds,Number of Inpatient Beds Occupied,Number of Adult Inpatient Beds Occupied,Number of Pediatric Inpatient Beds Occupied,Number of ICU Beds,Number of Adult ICU Beds,...,Number of Pediatric ICU Beds Occupied,Number of Adult Patients Hospitalized with COVID-19,Number of Pediatric Patients Hospitalized with COVID-19,Number of Adult Patients Hospitalized with Influenza,Number of Pedatric Patients Hospitalized with Influenza,Number of Adult Patients Hospitalized with RSV,Number of Pediatric Patients Hospitalized with RSV,Certifications,Percent of Adults ICU Beds Occupied,Cert_Counter
0,2023-12-08,WA,10650.0,9282.0,482.0,9040.0,8117.0,339.0,1623.0,1059.0,...,62.0,222.0,4.0,NaN,NaN,NaN,NaN,DWC/CARN/CRN/CBN/CBN/CPEN/DWC/CPEN/CPAN/ACS,79.792257,10
1,2023-12-08,WI,10752.0,9824.0,425.0,7574.0,7027.0,286.0,1566.0,1232.0,...,71.0,84.0,2.0,NaN,NaN,NaN,NaN,AOCNP/ACS/CARN/CRN,66.314935,4
2,2023-12-08,WV,4813.0,4556.0,256.0,3701.0,3562.0,139.0,639.0,595.0,...,23.0,47.0,0.0,NaN,NaN,NaN,NaN,CRN,74.957983,1
3,2023-12-08,WY,1318.0,1142.0,25.0,559.0,534.0,6.0,114.0,109.0,...,0.0,4.0,0.0,NaN,NaN,NaN,NaN,AOCNP/JCI/CARN/CBN/CARN/JCI/ACS,36.697248,7
4,2023-08-19,AK,1354.0,1192.0,77.0,1054.0,939.0,43.0,184.0,126.0,...,8.0,11.0,1.0,NaN,NaN,NaN,NaN,CARN/ISO/AOCNP/CARN,68.253968,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12763,2023-12-08,USA,681406.0,618736.0,37598.0,508063.0,465598.0,24107.0,98373.0,75984.0,...,6116.0,9333.0,442.0,NaN,NaN,NaN,NaN,CRN/ISO,71.000474,2
12764,2023-12-08,UT,5764.0,4535.0,361.0,3524.0,2881.0,254.0,911.0,520.0,...,34.0,35.0,4.0,NaN,NaN,NaN,NaN,CPEN/ISO/AOCNP/CARN/CARN/CPAN,64.230769,6
12765,2023-12-08,VA,16500.0,15161.0,911.0,11303.0,10467.0,594.0,2276.0,1856.0,...,121.0,155.0,6.0,NaN,NaN,NaN,NaN,CPAN/AOCNP/CPEN/DWC/CPEN/DWC/CPEN/CPEN/JCI/CCT...,64.008621,11
12766,2023-12-08,VI,168.0,152.0,16.0,89.0,82.0,3.0,17.0,14.0,...,0.0,1.0,0.0,NaN,NaN,NaN,NaN,CPEN/CPEN/AOCNP/CARN/CCTN/ISO/JCI/CPEN/CCTN/ACS,50.000000,10
12767,2023-12-08,VT,1171.0,1034.0,61.0,810.0,767.0,14.0,129.0,96.0,...,2.0,17.0,0.0,NaN,NaN,NaN,NaN,CPEN/CRN/ACS/CBN/ISO/ACS/JCI/ISO/CPAN/CPEN,67.708333,10

# Busca todos los hospitales que cumplan con la certificación CRN y déjalos en un *dataframe* llamado "CRNData".

In [55]:
CRNData = df[df['Certifications'].str.contains('CRN')]
CRNData

,Week Ending Date,Geographic aggregation,Number of Inpatient Beds,Number of Adult Inpatient Beds,Number of Pediatric Inpatient beds,Number of Inpatient Beds Occupied,Number of Adult Inpatient Beds Occupied,Number of Pediatric Inpatient Beds Occupied,Number of ICU Beds,Number of Adult ICU Beds,...,Number of Pediatric ICU Beds Occupied,Number of Adult Patients Hospitalized with COVID-19,Number of Pediatric Patients Hospitalized with COVID-19,Number of Adult Patients Hospitalized with Influenza,Number of Pedatric Patients Hospitalized with Influenza,Number of Adult Patients Hospitalized with RSV,Number of Pediatric Patients Hospitalized with RSV,Certifications,Percent of Adults ICU Beds Occupied,Cert_Counter
0,2023-12-08,WA,10650.0,9282.0,482.0,9040.0,8117.0,339.0,1623.0,1059.0,...,62.0,222.0,4.0,NaN,NaN,NaN,NaN,DWC/CARN/CRN/CBN/CBN/CPEN/DWC/CPEN/CPAN/ACS,79.792257,10
1,2023-12-08,WI,10752.0,9824.0,425.0,7574.0,7027.0,286.0,1566.0,1232.0,...,71.0,84.0,2.0,NaN,NaN,NaN,NaN,AOCNP/ACS/CARN/CRN,66.314935,4
2,2023-12-08,WV,4813.0,4556.0,256.0,3701.0,3562.0,139.0,639.0,595.0,...,23.0,47.0,0.0,NaN,NaN,NaN,NaN,CRN,74.957983,1
6,2023-08-19,AR,7453.0,6803.0,427.0,5201.0,4724.0,295.0,1143.0,865.0,...,76.0,91.0,6.0,NaN,NaN,NaN,NaN,CRN/AOCNP/AOCNP/JCI/AOCNP,73.063584,5
10,2023-08-19,CO,10249.0,8986.0,687.0,6741.0,5936.0,371.0,1642.0,1275.0,...,61.0,80.0,5.0,NaN,NaN,NaN,NaN,CRN/CPAN/JCI/CPEN/CCTN/CPEN/AOCNP,60.235294,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12754,2023-12-08,OK,8386.0,7568.0,409.0,5635.0,5137.0,281.0,1129.0,893.0,...,61.0,67.0,9.0,NaN,NaN,NaN,NaN,ACS/ACS/CARN/CRN/CBN/CBN/CBN,71.220605,7
12759,2023-12-08,SC,9823.0,9250.0,436.0,7510.0,7106.0,261.0,1591.0,1239.0,...,57.0,154.0,10.0,NaN,NaN,NaN,NaN,CBN/DWC/CPAN/ACS/CCTN/CRN/CRN,66.505246,7
12760,2023-12-08,SD,2150.0,1974.0,121.0,1402.0,1239.0,61.0,297.0,235.0,...,6.0,10.0,1.0,NaN,NaN,NaN,NaN,ISO/AOCNP/JCI/CBN/CBN/CRN,52.765957,6
12763,2023-12-08,USA,681406.0,618736.0,37598.0,508063.0,465598.0,24107.0,98373.0,75984.0,...,6116.0,9333.0,442.0,NaN,NaN,NaN,NaN,CRN/ISO,71.000474,2
12767,2023-12-08,VT,1171.0,1034.0,61.0,810.0,767.0,14.0,129.0,96.0,...,2.0,17.0,0.0,NaN,NaN,NaN,NaN,CPEN/CRN/ACS/CBN/ISO/ACS/JCI/ISO/CPAN/CPEN,67.708333,10

# Almacena el *dataframe* modificado y los *dataframes* creados en los pasos anteriores en un mismo archivo de Excel llamado "datosHospitalesProcesados.xlsx". Cada *dataframe* deberá estar en una hoja diferente.

In [ ]:

with pd.ExcelWriter('datosHospitalesProcesados.xlsx', engine='xlsxwriter') as writer:
    df.to_excel(writer, sheet_name='Original', index=False)
    filtro.to_excel(writer, sheet_name='Filtro', index=False)
    registros2024.to_excel(writer, sheet_name='Registro 2024', index=False)
    CRNData.to_excel(writer, sheet_name='CRNData', index=False)

: